services:
  mysql-container:
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=Conchosu@1
    volumes:
      - ./mydata1:/var/lib/mysql
      - ./backupv4.sql:/docker-entrypoint-initdb.d/backup.sql
    command: --init-file /docker-entrypoint-initdb.d/backup.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - image-volume:/app/static/images
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container/QuanLyNhaXe
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Conchosu@1
    depends_on:
      - mysql-container

  client-frontend:
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - webdata-client:/build

  admin-frontend:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - webdata-admin:/build

  driver-frontend:
    build:
      context: ./frontend/driver
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - webdata-driver:/build

  manager-frontend:
    build:
      context: ./frontend/manager
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - webdata-manager:/build

  web-server:
    image: nginx:1.25.4-alpine
    ports:
      - 10041:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - webdata-client:/usr/share/nginx/html/client
      - webdata-admin:/usr/share/nginx/html/admin
      - webdata-driver:/usr/share/nginx/html/driver
      - webdata-manager:/usr/share/nginx/html/manager
      - image-volume:/usr/share/nginx/html/images
    depends_on:
      - client-frontend
      - admin-frontend
      - driver-frontend
      - manager-frontend

volumes:
  mydata1:
  webdata-client:
  webdata-admin:
  webdata-driver:
  webdata-manager:
  image-volume: