export const GENDER_OPTION = [
    {
        value: 1,
        label: 'Nữ',
    },
    {
        value: 0,
        label: 'Nam',
    },
]

export const UPDATE_INFOR = [
    {
        id: 1,
        name: 'tel',
        type: 'text',
        placeholder: 'Số điện thoại',
        errorMessage: 'Sai số điện thoại',
        label: 'Số điện thoại',
        pattern: '^(0d{9,10}|+d{1,3}s?d{1,14})$',
        required: false,
        role: [1, 2, 3, 4, 5],
        editable: [1, 5],
    },
    {
        id: 2,
        name: 'name',
        type: 'text',
        placeholder: 'Họ và tên',
        errorMessage: 'Tên không quá 30 ký tự',
        label: 'Họ và tên',
        pattern: '^.{1,30}$',
        required: false,
        role: [1, 2, 3, 4, 5],
        editable: [2, 3, 4, 5],
    },
    {
        id: 3,
        name: 'email',
        type: 'email',
        placeholder: 'Email',
        errorMessage: '',
        label: 'Email',
        required: false,
        role: [1, 2, 3, 4, 5],
        editable: [2, 3, 4, 5],
    },
    {
        id: 4,
        name: 'gender',
        type: 'select',
        placeholder: 'Chọn giới tính',
        errorMessage: '',
        label: 'Giới tính',
        options: GENDER_OPTION,
        role: [1, 2, 3, 4, 5],
        editable: [],
    },
    {
        id: 5,
        name: 'address',
        type: 'text',
        placeholder: 'Địa chỉ',
        errorMessage: '',
        label: 'Địa chỉ',
        role: [2, 3, 4, 5],
        editable: [],
    },
    {
        id: 6,
        name: 'idCard',
        type: 'text',
        placeholder: 'CCCD',
        pattern: '^d{9}$|^d{12}$',
        errorMessage: 'CCCD chỉ chứa 9 hoặc 12 số',
        label: 'CCCD',
        role: [2, 3, 4, 5],
        editable: [2, 3, 4, 5],
    },
    {
        id: 7,
        name: 'beginWorkDate',
        type: 'text',
        placeholder: 'Work Day',
        pattern: '',
        errorMessage: '',
        label: 'Ngày làm việc',
        role: [2, 3, 4, 5],
        editable: [2, 3, 4, 5],
    },
    {
        id: 8,
        name: 'licenseNumber',
        type: 'text',
        placeholder: 'Số bằng lái',
        pattern: '',
        errorMessage: '',
        label: 'Số hiệu bằng lái',
        role: [4],
        editable: [4],
    },
    {
        id: 9,
        name: 'issueDate',
        type: 'text',
        placeholder: 'Ngày cấp bằng',
        pattern: '',
        errorMessage: '',
        label: 'Ngày cấp bằng lái',
        role: [4],
        editable: [4],
    },
]

export const companyInput = {
    firmName: {
        id: 1,
        name: 'firmName',
        type: 'text',
        placeholder: 'Nhập tên hãng xe',
        errorMessage: 'Tên hãng xe không được để trống',
        label: 'Tên hãng xe',
        pattern: '^.+$',
        required: true,
    },
    representName: {
        id: 2,
        name: 'representName',
        type: 'text',
        placeholder: 'Nhập tên người đại diện',
        errorMessage: 'Tên người đại diện không được để trống',
        label: 'Tên người đại diện',
        pattern: '^.{6,}$',
        required: true,
    },
    email: {
        id: 3,
        name: 'email',
        type: 'email',
        placeholder: 'Nhập email',
        errorMessage: 'Email không hợp lệ',
        label: 'Email',
        pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$',
        required: true,
    },
    idCard: {
        id: 4,
        name: 'idCard',
        type: 'text',
        placeholder: 'Nhập số CCCD',
        errorMessage: 'CCCD không hợp lệ',
        label: 'CCCD',
        pattern: '^[0-9]{9,12}$',
        required: true,
    },
    telephone: {
        id: 5,
        name: 'telephone',
        type: 'text',
        placeholder: 'Nhập số điện thoại',
        errorMessage: 'Số điện thoại không hợp lệ',
        label: 'Nhập số điện thoại',
        pattern: '^(0d{9,10}|+d{1,3}s?d{1,14})$',
        required: true,
    },
    businessLicense: {
        id: 6,
        name: 'businessLicense',
        type: 'text',
        placeholder: 'Nhập số giấy phép kinh doanh',
        errorMessage: 'Số giấy phép không để trống',
        label: 'Số GPKD',
        pattern: '^.+$',
        required: true,
    },
    address: {
        id: 6,
        name: 'address',
        type: 'text',
        placeholder: 'Nhập địa chỉ',
        errorMessage: 'Địa chỉ không được để trống',
        label: 'Địa chỉ',
        pattern: '^.+$',
        required: true,
    },
}

export const COLOR_STATE = {
    success: 'green',
    pending: '#9a9a0f',
    cancel: 'red',
    info: 'blue',
}

export const dayInWeek = [
    'Thứ hai',
    'Thứ ba',
    'Thứ tư',
    'Thứ năm',
    'Thứ sáu',
    'Thứ bảy',
    'Chủ nhật',
]

export const dayInWeekSum = ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'CN']

export const MONTH_IN_YEAR = [
    'Tháng một',
    'Tháng hai',
    'Tháng ba',
    'Tháng tư',
    'Tháng năm',
    'Tháng sáu',
    'Tháng bảy',
    'Tháng tám',
    'Tháng chín',
    'Tháng mười',
    'Tháng mười một',
    'Tháng mười hai',
]

export const COLOR = ['info', 'warning', 'success', 'danger', 'dark', 'light']

export const TIME_TABLE = {
    morning: {
        label: 'Sáng',
        from: 6,
        to: 12,
        color: 'success',
    },
    afternoon: {
        label: 'Chiều',
        from: 12,
        to: 18,
        color: 'primary',
    },
    evening: {
        label: 'Tối',
        from: 18,
        to: 24,
        color: 'infor',
    },
    late: {
        label: 'Khuya',
        from: 0,
        to: 6,
        color: 'warning',
    },
}
