name: Deploy to Server

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: ${{ secrets.HOST_PORT }}
        script: |
          cd project/20110248_20110315/KhoaLuanTotNghiep-final
          git pull
          echo "${{ secrets.FRONTEND_ADMIN_ENV }}" > frontend/admin/.env
          echo "${{ secrets.FRONTEND_CLIENT_ENV }}" > frontend/client/.env
          echo "${{ secrets.FRONTEND_DRIVER_ENV }}" > frontend/driver/.env
          echo "${{ secrets.FRONTEND_MANAGER_ENV }}" > frontend/manager/.env
          echo "${{ secrets.CHATBOT_ENV }}" > backend/src/main/python/.env
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > backend/src/main/resources/application.properties
          docker-compose up -d
